gitbaseURL = 'http://ops2devops.tanzu.dk'
languageCode = 'en-us'
title = 'Tanzu.dk'
theme = "hyde"

[Menus]
  main = [
      {Name = "Main Github Repo", URL = "https://github.com/TanzuDK/ops2devops"},
  ]

  [params]
    description = "Ops2DevOps training"
    themeColor = "theme-base-0d"

[author]
    name = "Robert Jensen"
    homepage = "https://www-.robert-jensen.dk"